name: drinkwaterpro
description: Drinkwater.pro

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.5+1

environment:
  sdk: '>=2.18.0-157.0.dev <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  firebase_messaging: ^14.0.4
  restart_app: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  mvc_pattern: ^7.0.0
  http: ^0.13.3
  font_awesome_flutter: ^10.1.0
  sliding_up_panel: ^2.0.0+1
  geolocator: ^8.2.0
  pinput: ^2.2.16
  sqflite: any
  path_provider: ^2.0.6
  intl_phone_field: ^3.1.0
  flutter_multi_formatter: ^2.5.1
  intl: ^0.17.0
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner
      ref: flutter-beta
  flutter_yookassa_sdk: ^0.1.2
  http_client: ^1.0.3
  dropdown_button2: ^1.4.0
  permission_handler: ^9.2.0
  google_maps_flutter: ^2.2.1
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.1.0
  flutter_native_splash: ^2.2.3+1
  percent_indicator: ^4.2.2
  mqtt_client: ^9.7.1
  flutter_polyline_points: ^1.0.0
  video_player: ^2.4.7
  firebase_core: ^2.3.0
  firebase_analytics: 10.0.3
  firebase_messaging: ^14.1.3
  package_info_plus: ^1.0.6
  flutter_fgbg: ^0.2.1
  url_launcher: ^6.1.7
  flutter_local_notifications: ^12.0.4
  firebase_in_app_messaging: ^0.7.0+7



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon_market.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/
    - assets/img/
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 500